# Generated by Django 5.2.10 on 2026-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto_binaria',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainer_sprite',
            field=models.CharField(default='trainer_red.png', max_length=255),
        ),
    ]
