# Generated by Django 5.2.10 on 2026-04-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Object",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("name", models.CharField(max_length=100)),
        ("description", models.TextField()),
        ("effect_type", models.CharField(max_length=50)),
        ("effect_value", models.FloatField()),
        (
          "rarity",
          models.CharField(
            choices=[
              ("COMMON", "Common (60%)"),
              ("UNCOMMON", "Uncommon (30%)"),
              ("RARE", "Rare (10%)"),
              ("LEGENDARY", "Legendary (2%)"),
            ],
            default="COMMON",
            max_length=20,
          ),
        ),
        (
          "vfx_type",
          models.CharField(
            choices=[
              ("HEAL", "Green Crosses"),
              ("BUFF_ATK", "Red Sword Aura"),
              ("BUFF_DEF", "Blue Shield Aura"),
              ("BUFF_SPEED", "Yellow Wings"),
              ("REVIVE", "Golden Glow"),
              ("EQUIP", "Sparkle Static"),
            ],
            default="HEAL",
            max_length=20,
          ),
        ),
      ],
    ),
    migrations.CreateModel(
      name="Inventory",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        (
          "user",
          models.OneToOneField(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="inventory",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
    ),
    migrations.CreateModel(
      name="InventoryItem",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("quantity", models.IntegerField(default=1)),
        (
          "inventory",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="items",
            to="inventory.inventory",
          ),
        ),
        (
          "object",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to="inventory.object"
          ),
        ),
      ],
    ),
  ]
