# Generated by Django 6.0.3 on 2026-04-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("inventory", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="object",
      name="sprite",
      field=models.URLField(blank=True, max_length=500, null=True),
    ),
  ]
