# Generated by Django 5.2.10 on 2026-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_id_alter_inventoryitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common (60%)'), ('UNCOMMON', 'Uncommon (30%)'), ('RARE', 'Rare (10%)'), ('LEGENDARY', 'Legendary (2%)')], default='COMMON', max_length=20),
        ),
        migrations.AddField(
            model_name='object',
            name='vfx_type',
            field=models.CharField(choices=[('HEAL', 'Green Crosses'), ('BUFF_ATK', 'Red Sword Aura'), ('BUFF_DEF', 'Blue Shield Aura'), ('BUFF_SPEED', 'Yellow Wings'), ('REVIVE', 'Golden Glow'), ('EQUIP', 'Sparkle Static')], default='HEAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
