sonar.projectKey=sonnar_videogame
sonar.projectName=sonnar_videogame
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_69259d3730da918cd5ac8b534eefd8f78227209e

# Define source directories
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx,**/*.css
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts

# Define test directories (if you have tests)
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts
# If you have a test coverage file generated (for example by Jest or Vitest)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
