sonar.projectKey=game
sonar.projectName=game
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.inclusions=**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**,**/tests.py,**/test_*.py
sonar.tests=.
sonar.test.inclusions=**/tests.py,**/test_*.py
