# Generated by Django 5.2.10 on 2026-04-01 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
      name="Ability",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("name", models.CharField(max_length=100)),
        ("damage_multiplier", models.FloatField()),
        ("effect", models.CharField(blank=True, max_length=100, null=True)),
        ("effect_probability", models.FloatField()),
      ],
    ),
    migrations.CreateModel(
      name="Type",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("name", models.CharField(max_length=50)),
      ],
    ),
    migrations.CreateModel(
      name="Creature",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("name", models.CharField(max_length=100)),
        ("pokedex_id", models.IntegerField(blank=True, null=True, unique=True)),
        ("hp", models.IntegerField()),
        ("attack", models.IntegerField()),
        ("defense", models.IntegerField()),
        ("special_attack", models.IntegerField()),
        ("special_defense", models.IntegerField()),
        ("speed", models.IntegerField()),
        (
          "front_sprite",
          models.URLField(blank=True, max_length=500, null=True),
        ),
        ("back_sprite", models.URLField(blank=True, max_length=500, null=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "type_1",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="creatures_main",
            to="creatures.type",
          ),
        ),
        (
          "type_2",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name="creatures_secondary",
            to="creatures.type",
          ),
        ),
      ],
    ),
    migrations.CreateModel(
      name="CreatureAbility",
      fields=[
        (
          "id",
          models.AutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        (
          "ability",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to="creatures.ability"
          ),
        ),
        (
          "creature",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, to="creatures.creature"
          ),
        ),
      ],
      options={
        "unique_together": {("creature", "ability")},
      },
    ),
  ]
