# Generated by Django 5.2.10 on 2026-03-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(blank=True, max_length=50, null=True)),
                ('front_sprite', models.URLField(max_length=500)),
                ('back_sprite', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='creatures.pokemon')),
                ('to_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_evolutions', to='creatures.pokemon')),
            ],
        ),
    ]
