# Generated by Django 6.0.4 on 2026-04-22 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect_type', models.CharField(choices=[('PARALYZE', 'Paralyze - Reduce opponent speed by 75%'), ('BURN', 'Burn - Reduce opponent attack by 50%'), ('FREEZE', 'Freeze - Opponent skips next turn'), ('POISON', 'Poison - Damage per turn'), ('CONFUSION', 'Confusion - Opponent may attack self'), ('SLEEP', 'Sleep - Opponent sleeps for 1-3 turns')], max_length=20)),
                ('trigger_probability', models.FloatField(default=0.3, help_text='Probability of triggering this ability (default 30%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='creatureability',
            options={'ordering': ['creature', 'slot']},
        ),
        migrations.AlterUniqueTogether(
            name='creatureability',
            unique_together={('creature', 'ability')},
        ),
        migrations.AddField(
            model_name='ability',
            name='ability_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abilities', to='creatures.type'),
        ),
        migrations.AddField(
            model_name='ability',
            name='base_damage',
            field=models.PositiveIntegerField(default=20, help_text='Base damage of the ability'),
        ),
        migrations.AddField(
            model_name='creatureability',
            name='slot',
            field=models.PositiveIntegerField(choices=[(1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3'), (4, 'Slot 4')], default=1, help_text='Ability slot (1-4)'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='damage_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ability',
            name='effect',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ability',
            name='effect_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creatureability',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creature_abilities', to='creatures.creature'),
        ),
        migrations.AlterUniqueTogether(
            name='creatureability',
            unique_together={('creature', 'ability'), ('creature', 'slot')},
        ),
        migrations.AddField(
            model_name='creature',
            name='special_ability',
            field=models.ForeignKey(blank=True, help_text='Passive ability that triggers with 30% probability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatures', to='creatures.specialability'),
        ),
    ]
