# Generated by Django 5.2.10 on 2026-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='vfx_type',
            field=models.CharField(choices=[('FIRE_FX', 'Red Flames'), ('WATER_FX', 'Blue Bubbles'), ('GRASS_FX', 'Green Leaves'), ('ELECTRIC_FX', 'Yellow Sparks'), ('PHYSICAL_HIT', 'Red Screen Shake'), ('SPECIAL_HIT', 'Purple Screen Flash')], default='PHYSICAL_HIT', max_length=20),
        ),
    ]
