# Generated by Django 6.0.3 on 2026-04-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='base_power',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='ability',
            name='move_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='creatures.type'),
        ),
        migrations.AddField(
            model_name='creature',
            name='special_ability_effect',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='special_ability_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='special_ability_probability',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='ability',
            name='damage_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ability',
            name='effect',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ability',
            name='effect_probability',
            field=models.FloatField(default=0.0),
        ),
    ]
