# Generated by Django 6.0.3 on 2026-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0002_ability_base_power_ability_move_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
