# Generated by Django 5.2.10 on 2026-04-03 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Battle",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        (
          "status",
          models.CharField(
            choices=[
              ("waiting", "Waiting"),
              ("playing", "Playing"),
              ("finished", "Finished"),
            ],
            default="waiting",
            max_length=20,
          ),
        ),
        (
          "turn_number",
          models.PositiveIntegerField(
            default=1, validators=[django.core.validators.MinValueValidator(1)]
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "current_turn",
          models.ForeignKey(
            blank=True,
            help_text="Player whose turn it is",
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="battle_turns",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "player1",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="p1",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "player2",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="p2",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "winner",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
    ),
  ]
