# Generated by Django 6.0.3 on 2026-03-31 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Battle",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        ("status", models.CharField(max_length=20)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "player1",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="p1",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "player2",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="p2",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "winner",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
    ),
  ]
