# Generated by Django 4.2 on 2026-04-01 01:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ("combat", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="battle",
      name="current_turn",
      field=models.ForeignKey(
        blank=True,
        help_text="Player whose turn it is",
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name="battle_turns",
        to=settings.AUTH_USER_MODEL,
      ),
    ),
    migrations.AddField(
      model_name="battle",
      name="turn_number",
      field=models.PositiveIntegerField(
        default=1, validators=[django.core.validators.MinValueValidator(1)]
      ),
    ),
    migrations.AddField(
      model_name="battle",
      name="updated_at",
      field=models.DateTimeField(auto_now=True),
    ),
    migrations.AlterField(
      model_name="battle",
      name="id",
      field=models.AutoField(
        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
      ),
    ),
    migrations.AlterField(
      model_name="battle",
      name="status",
      field=models.CharField(
        choices=[
          ("waiting", "Waiting"),
          ("playing", "Playing"),
          ("finished", "Finished"),
        ],
        default="waiting",
        max_length=20,
      ),
    ),
  ]
