# Generated by Django 4.2 on 2026-04-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("combat", "0002_battle_current_turn_battle_turn_number_and_more"),
  ]

  operations = [
    migrations.AlterField(
      model_name="battle",
      name="id",
      field=models.BigAutoField(
        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
      ),
    ),
  ]
